export const ALL_RENT_REQUEST = "ALL_RENT_REQUEST";
export const ALL_RENT_SUCCESS = "ALL_RENT_SUCCESS";
export const ALL_RENT_FAIL = "ALL_RENT_FAIL";

export const RENT_REQUEST = "RENT_REQUEST";
export const RENT_SUCCESS = "RENT_SUCCESS";
export const RENT_FAIL = "RENT_FAIL";

export const MY_BOOKINGS_REQUEST = "MY_BOOKINGS_REQUEST";
export const MY_BOOKINGS_SUCCESS = "MY_BOOKINGS_SUCCESS";
export const MY_BOOKINGS_FAIL = "MY_BOOKINGS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";