export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const DRIVER_LOGIN_REQUEST = "DRIVER_LOGIN_REQUEST";
export const DRIVER_LOGIN_SUCCESS = "DRIVER_LOGIN_SUCCESS";
export const DRIVER_LOGIN_FAIL = "DRIVER_LOGIN_FAIL";

export const REGISTER_DRIVER_REQUEST = "REGISTER_DRIVER_REQUEST";
export const REGISTER_DRIVER_SUCCESS = "REGISTER_DRIVER_SUCCESS";
export const REGISTER_DRIVER_FAIL = "REGISTER_DRIVER_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";